---
title: "Lecture 12. Final Project and Website"
author: Marcy Shieh
date: December 3, 2020
output: beamer_presentation
---

# Goals

- Discuss final presentation and project

- Discuss web presence

# Logistics

- Please submit Exercise 10 ASAP!!

- Last day to submit your exercises is December 10th!!

- I will NOT post the answer keys or provide comments until everyone has submitted Exercise 10 (lol this was the best threat I could come up with)

# Evaluations

- Please submit instructor evaluations for this course (Due: December 10th)

- I only see them if at least 5 people (so all of you) submit evaluations

- This helps me with teaching the course going forward

- In non-pandemic times, I would have brought in homebaked goods

# Final Presentation: Overview

- Due: December 10th (in class)

- No more than 7-10 minutes long

- Your colleagues can ask you questions during Q&A and can provide more extensive comments in the Slack

# Final Presentation: Requirements

- Beamer presentation (this should be on GitHub)

- Needs to cover all basic components of a coherent Data & Methods section

# Final Presentation: Requirements (cont)

- Slide 1: Background and research question

- Slide 2: Hypotheses

- Slide 3: Data

- Slide 4: Descriptive summary of data

- Slide 5: Method

- Slide 6: Results

- Slide 7: Discussion & Conclusion

# Final Project: Overview

- Due: December 21st by 12pm CST

- No page minimum or maximum

# Final Project: Requirements

You need to send me an email to a GitHub repository URL that contains the following:

- Write-up (written in R Markdown papaja template) that includes all the topics covered in your presentation

- Datasets

- R code for data manipulation, data summary, graphics, and analyses

- Ideally, I can download this RProject and replicate everything in your paper

# Questions?

- The idea is that you should be able to just copy and paste sections from your seminar papers and submit it as the write-up for this class

- The only "additional" thing (IMO) are the replication files, which you would need to have if you were submitting to a top journal

- I realize that submitting to this class is very much unlike submitting to a top journal, but this is called *practice*

# Web Presence

- In our increasingly technological world, it is important to establish a web presence...

- If you have seen my website (or Twitter, tbh), you know I am the wrong person to teach this since I created a website specifically for this class and I just live tweet TV shows on my Twitter (because it's a pandemic and I have no life)

- I will, however, show you some examples of *good* professional websites

# Some Thoughts on Academic Twitter

- Again, I am the wrong person to ask about because I run a TV Twitter, but here are my unsolicited two cents...

- Academic Twitter is great for...

    - promoting your own work
    - seeing what your favorite researchers are working on
    - seeing what has recently been published in the top journals
    - upcoming conferences/events in your (sub)subfield
    - staying connected with people you meet at conferences
    - asking for advice on teaching, resources, etc.
    - most academics tend to follow you back if your bio indicates that you're also an academic
    - get some insight on what people think about academic culture but be wary that this might not be representative

# Examples of Websites

- Basic website (Weebly): http://www.dillonlaaker.org/

- More involved site (Weebly): https://www.eleanorneffpowell.com/

- More involved website (Wordpress): http://annameier.net/

- More involved website (Squarespace): https://chagaimweiss.com/

- More involved website (Squarespace): https://www.loadeline.com/

- GitHub Pages website: https://mikedecr.github.io/

- GitHub Pages website: https://www.shirikov.com/
    
# Examples of Bookdown Pages

- I just learned how to create Bookdown pages recently

- I would totally use it for all my classes going forward

- I think you would find it helpful for teaching and collaborative work