---
title: 'Exercise 5: Functions'
author: "Marcy Shieh"
date: "9/24/2020"
output: pdf_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

# Prerequisites

1. Open you `ps811-exercises` folder.

2. Go to File > New File > R Script.

3. Save file as `exercise-6-functions.R`.

4. Load R packages installed in Lectures 5 and 6.

5. Download the [national.csv file from Kaggle](https://www.kaggle.com/umichigan/world-religions).

6. Load the CSV file into your R environment.

7. View the CSV.

# Loops

1. Write a loop to find how many variables there are per observations.

2. Find the mean number of Protestant Christians in each country (i.e., the state column) using `tapply()` in both base R and Tidyverse.

3. Check the column type for each variable that is just characters.

    Hint: You can use `sapply(dataset-name-here, class)`.

4. Log the buddhism variables.

5. Write a function that lists all the unique years with more than 300,000 Christians in total.

6. Group by the code variable.

    Hint: Use nesting.

7. Create a model column. You need to include a linear regression model that examines whether the proportion of Jews (judaism_percent) affect whether a country has dual religions.

8. Extract the coefficients into a new column

9. Look at the coefficients.

10. Pull out the model column.

11. Unnest the coefficients column.